<a href="https://colab.research.google.com/github/PhinyadaPhen/Multivariate/blob/main/Function_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Funcion


```python
def functon_name(_Input_):
    do_something with _Input_ to produce _Output_
    return _Output_
```

function มีส่วนสำคัญทั้งหมด 4 ส่วน 


1.   บอก Python ว่าเราจะเขียนฟังก์ชัน ชื่ออะไร def fuction_name(): (ขาดไม่ได้)
2.   กำหนดตัวแปรที่จะเป็น input (ขาดได้)
3.   ส่วนประมวลผล do_sth with Input to get Output (ขาดไม่ได้)
4.   ส่วน Output return Output (ขาดได้)





In [1]:
def print_name(name,surname,ID):
    st = f' ชื่อ {name} นามสกุล {surname} ID {ID}' 
    return st

####การเรียกใช้ฟังก์ชั่น

In [2]:
print_name('กิตติมา' , 'อุปสุข' , '623021040-9')

' ชื่อ กิตติมา นามสกุล อุปสุข ID 623021040-9'

In [3]:
output_string = print_name('กิตติมา' , 'อุปสุข' , '623021040-9')
print(output_string)

 ชื่อ กิตติมา นามสกุล อุปสุข ID 623021040-9


#### ฟังก์ชั่นไม่จำเป็นต้องมี Output

In [4]:
def print_name2(surname,ID,name):
    st = f'ชื่อ {name} นามสกุล {surname} รหัส {ID}'
    print(st)

In [5]:
print_name('กิตติมา' , 'อุปสุข' , '623021040-9')

' ชื่อ กิตติมา นามสกุล อุปสุข ID 623021040-9'

In [6]:
op2 = print_name2('กิตติมา' , 'อุปสุข' , '623021040-9')

ชื่อ 623021040-9 นามสกุล กิตติมา รหัส อุปสุข


In [7]:
print(op2)

None


In [8]:
def Pi():
    return 3.14159265359

In [9]:
#คำนวณพื้นที่วงกลมที่มีขนาดเส้นผ่านศูนย์กลางเท่ากับ 3 
Pi()*(1.5**2)

7.0685834705775

In [10]:
def print_my_name():
    print('ภิญญาดา เพ็ญสุข 623021052-2')

In [11]:
print_my_name()

ภิญญาดา เพ็ญสุข 623021052-2


### input ของ Function ใน Python มี 2 แบบคือ input ที่จำเป็นต้องใส่ กับ input ที่ไม่จำเป็นต้องใส่ (มีค่า default) เราต้องเรียง input ที่จำเป็นต้องใส่ขึ้นก่อน




In [12]:
def print_2lines_default(name,surname,ID,grade='F'):
    st = f'ชื่อ {name} นามสกุล {surname} รหัส {ID}'
    print(st)
    st2=f'เกรดวิชา Multivariate >>> {grade}'
    print(st2)

In [13]:
print_2lines_default('ภิญญาดา','เพ็ญสุข','623021052-2','A')

ชื่อ ภิญญาดา นามสกุล เพ็ญสุข รหัส 623021052-2
เกรดวิชา Multivariate >>> A


#### เราสามารถเรียกฟังก์ชั่นโดยใช้ชื่อตัวแปรของฟังก์ชั่นช่วยได้

In [14]:
print_name2(name='กิตติมา', surname='อุปสุข', ID='623021040-9')

ชื่อ กิตติมา นามสกุล อุปสุข รหัส 623021040-9


HW3 ให้เขียน function คำนวณจำนวนวินาทีจาก เวลาต่อไปนี้

'14-15-31'

'13-00-01'

'05-49-44'

'00-00-16'

และ print ให้สวยงาม


In [15]:
def tid(time):
    tid = f'เวลาที่โจทย์กำหนดมาให้ คือ {time}'
    timeee = time.split('-')
    print(tid)
    a = int (timeee[0])*3600
    b = int (timeee[1])*60
    c = int (timeee[2])
    total = a+b+c
    tid2=f'คำนวณเป็นวินาทีได้ {total} วินาที '
    print(tid2)

In [16]:
tid('14-15-31')

เวลาที่โจทย์กำหนดมาให้ คือ 14-15-31
คำนวณเป็นวินาทีได้ 51331 วินาที 


In [17]:
tid('13-00-01')

เวลาที่โจทย์กำหนดมาให้ คือ 13-00-01
คำนวณเป็นวินาทีได้ 46801 วินาที 


In [18]:
tid('05-49-44')

เวลาที่โจทย์กำหนดมาให้ คือ 05-49-44
คำนวณเป็นวินาทีได้ 20984 วินาที 


In [ ]:
tid('00-00-16')

เวลาที่โจทย์กำหนดมาให้ คือ 00-00-16
คำนวณเป็นวินาทีได้ 16 วินาที 


Numpy -> package สำหรับจัดการกับ Array ที่เป็นตัวเลข (Matrix)

Num + py -> Number-Numerical + python

การใช้ package
1. ```import``` ```ชื่อ package``` #เรียกใช้ package
2. ```ชื่อ package``` . ```ชื่อฟังก์ชัน``` #เรียกใช้ function

data structure -> array

สร้าง Numpy array

In [20]:
import numpy

In [21]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


ชี้ค่าใน numpy array

In [22]:
mat_ex1[1,1] #[แถว,หลัก]  แถวแนวนอนเริ่มจากแถว0,หลักแนวตั้งเริ่มจากหลัก0 

0.1

ถ้าไม่มี numpy array 

In [23]:
list_ex1 = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
print(list_ex1)

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]


In [24]:
list_ex1[1][1]

0.1

In [25]:
print(list_ex1)
a = list_ex1[1]
print(a)
print(a[1])

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]
[9.1, 0.1, 0.3]
0.1


Metrix Operations

data 2 แบบ -> matrix (2D array), scalar(ตัวเลขค่าคงที่)

In [26]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)
mat_ex2 = numpy.array([[2,3.7,5.9],[91,1.5,7.3]])
print(mat_ex2)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]


##บวกกับลบ matrix เอาตัวเลขตำแหน่งเดียวกันมาบวกหรือลบกัน

In [30]:
mat_ex0 = numpy.array([[1,2],[3,4]])
print(mat_ex0)

[[1 2]
 [3 4]]


In [29]:
mat_ex3 = mat_ex1 + mat_ex2 
print(mat_ex3)
mat_ex4 = mat_ex1 - mat_ex2 
print(mat_ex4)

[[  7.2   6.7  10.4]
 [100.1   1.6   7.6]]
[[  3.2  -0.7  -1.4]
 [-81.9  -1.4  -7. ]]


In [31]:
mat_ex1 + mat_ex0 #ถ้าจำนวนเมทริกซ์ไม่เท่ากันจะไม่สามารถบวกหรือลบกันได้ 

ValueError: ignored

###การตรวจสอบขนาดของ matrix

In [32]:
mat_ex3.shape

(2, 3)

In [33]:
mat_ex3.shape[0]

2

##การคูณ matrix

In [35]:
print(mat_ex1)
print(mat_ex2)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]


In [34]:
mat_ex1 * mat_ex2

array([[1.040e+01, 1.110e+01, 2.655e+01],
       [8.281e+02, 1.500e-01, 2.190e+00]])

In [36]:
numpy.dot(mat_ex1,mat_ex2) 

ValueError: ignored

##การคูณ matrix (แถว*หลัก)

(หลักของ Matrix ตัวข้างหน้า ต้องเท่ากับ แถวของ Matrix ตัวข้างหลัง)

dot product ((AAA,x),(x,ZZZ)) = (AAA,ZZZ)

In [37]:
print(mat_ex1)
print(mat_ex1.shape)
print(mat_ex2)
print(mat_ex2.shape)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
(2, 3)
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]
(2, 3)


# Transpose กลับแถวเป็นหลักกลับหลักเป็นแถว

 ```matrix.T```  

In [39]:
print(mat_ex2)
print(mat_ex2.shape)

[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]
(2, 3)


In [40]:
print(mat_ex2.T)
print(mat_ex2.T.shape)

[[ 2.  91. ]
 [ 3.7  1.5]
 [ 5.9  7.3]]
(3, 2)


In [38]:
numpy.dot(mat_ex1,mat_ex2.T) #(2,3).(3,2)

array([[ 48.05, 510.55],
       [ 20.34, 830.44]])

In [42]:
numpy.dot(mat_ex1.T,mat_ex2) #(3,2).(2,3) = (3,3)

array([[838.5 ,  32.89,  97.11],
       [ 15.1 ,  11.25,  18.43],
       [ 36.3 ,  17.1 ,  28.74]])

HW4 อธิบายการหา Determinant และ Inverse matrix (รูปและคำอธิบาย)


~pandas~